server:
  applicationConnectors:
    - type: http
      port: 7200

  adminConnectors:
    - type: http
      port: 7201

redisConfiguration:
  password: ${REDIS_PASSWORD}
  master: ${REDIS_MASTER}
  sentinels: ${REDIS_SENTINELS}
  prefix: ${REDIS_PREFIX}
  database: ${REDIS_DATABASE:-0}
  maxTotal: 50
  maxWaitMillis: 100
  maxIdle: 25
  minIdle: 25
  testOnBorrow: true
  blockWhenExhausted: true
  redisEnabled: ${REDIS_ENABLED:true}  # override via env var; defaults to true for backward compatibility

cacheRefreshExecutorServiceConfig:
  minThreads: 1
  maxThreads: 3
  queueSize: 10

staticCacheRefreshConfig:
  nodeDefinitionConfig: 5
  workflowConfig: 5

cacheMaxEntriesConfig:
  nodeDefinitionConfig: 1000 # 100 nodes, 10 versions each
  workflowConfig: 1000 # 100 workflows, 10 versions each

lookupPropertiesPath: ${ENUM_STORE_BUCKET}

hbasePropertiesPath: ${HBASE_CONFIG_BUCKET}

authPropertiesPath: ${AUTH_PATH}

workflowPropertiesPath: ${WORKFLOW_PROPERTY_PATH}

hbaseNamespaceConfig:
  hot: ${HBASE_NAMESPACE_HOT:-ims_hot}
  cold: ${HBASE_NAMESPACE_COLD:-ims_cold}
  archival: ${HBASE_NAMESPACE_ARCHIVAL:-ims_archive}
  audit: ${HBASE_NAMESPACE_AUDIT:-ims_audit}

prometheusConfig:
  port: 9090
  path: "/metrics"

awaitTerminationTimeoutInSec: 20

workerDynamicOptions:
  workflowTaskPoller: 20
  activityTaskPoller: 50
  workflowCacheSize: 600
  maxWorkflowThreadCount: 800

# Optional Hadoop identity parameters for HBase connection
hadoopUserName: ${HADOOP_USERNAME}
hadoopLoginUser: ${HADOOP_LOGIN_USER}

temporalTaskQueue: ${TEMPORAL_TASK_QUEUE}
temporalFrontEnd: ${TEMPORAL_FRONTEND}
